### ISSUE TITLE
http2Server.HandleStreams received bogus greeting from client

### ISSUE THREAD

**Issue by dirien** [opencontrolplane/civo-opencontrolplane#1]
Hi,

when I try to run the code locally in my IDE, I get all the time following error message:

```bash
{"level":"info","msg":"[core] [Server #1] grpc: Server.Serve failed to create ServerTransport: connection error: desc = \"transport: http2Server.HandleStreams received bogus greeting from client: \\\"GET /api?timeout=32s HTT\\\"\"","system":"system","time":"2023-03-04T14:20:18Z"}
```

My `kubeconfig` looks like this:

```yaml
apiVersion: v1
clusters:
  - cluster:
      server: http://localhost:8080
    name: kubernetes
contexts:
  - context:
      cluster: kubernetes
      user: admin
    name: opencp-lon
current-context: opencp-lon
kind: Config
preferences: {}
users:
  - name: admin
    user:
      token: xxx
```

Any hints, what could be the possible error and how to run the civo-cp locally?
